export const LOGFILE = "colyseus.log";
export const PLAYER_HEALTH = 100;
export const GAME_PROCEDURES = {
  GET_PLAYER_DATA_BY_ID: "GET_PLAYER_DATA_BY_ID",
  INSERT_ACTION_LOG: "INSERT_ACTION_LOG",
  GET_MONSTER_DATA_BY_ID: "GET_MONSTER_DATA_BY_ID",
};
